### ISSUE TITLE
BUG: Correct style.css issues

### ISSUE THREAD

**Issue by lincolnpowell** [ReshelleCarbaugh/musician-website#10]
**Deliverables**:

- Correct or comment out the following reported issues from style.css:
    - Line 8: Cannot resolve file 'selenagomez3.png'
        - Add image to /assets and update url to reflect changes.
    - Line 12: Property padding-left duplicates property padding-left
        - Remove this line.
    - Line 36: Unit of measure 'px' is redundant
        - Remove "px" from `margin: 0px` and add `;` to end of value. 
    - Line 45: Mismatched property value (normal | bold | bolder | lighter | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | [initial | inherit | unset | revert])
        - Remove "px" from `font-weight: 100px;`. 
    - Line 47: ';' expected
        - Add `;` to end of value. 
    - Line 60: Mismatched parameters ([[<angle> | to? <side-or-corner>] ,]? <color-stop> [, <color-stop>]+)
        - Finish CSS property value for `background: linear-gradient(45deg, )`. 
    - Line 89: ';' expected
        - Add `;` to end of value.

**Comment by ReshelleCarbaugh** [comment]
**Deliverable Notes:**

-  Line 12 duplication has been removed. 
-  Line 36 value has been updated.
-  Line 47 value has been updated.
-  Line 89 value has been updated.

**The following lines still need to be updated**

- Line 8
- Line 45
- Line 60

**Comment by lincolnpowell** [comment]
@ReshelleCarbaugh Is the fixes for lines 12, 36, 47 and 89 going to be updated in the repository (thus actually completed) or are they going to be coupled with the outstanding issues on lines 8, 45 and 60?
